services:
  - type: web
    name: smart-campus-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: smart_campus
      - key: JWT_SECRET
        sync: false
